//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsEntityClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modify { get; set; }
        public string Editor { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Correct { get; set; }
        public int Quest_Id { get; set; }
    
        public virtual Quest Quest { get; set; }
    }
}
