//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsEntityClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestProram
    {
        public int Id { get; set; }
        public int Program_Id { get; set; }
        public int Quest_Id { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Quest Quest { get; set; }
    }
}
