//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsEntityClassLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    
    public partial class Variant
    {
        public ObservableCollection<QuestItem> GetChildren
        {
            get { return this.QuestItems; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variant()
        {
            this.QuestItems = new ObservableCollection<QuestItem>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modify { get; set; }
        public string Editor { get; set; }
        public int Chapter_Id { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<QuestItem> QuestItems { get; set; }
    }
}
